import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import Navigation from "./components/Navigation";

const poppins = Poppins({
  weight: "800",
  subsets: ['latin'] 
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{backgroundColor: "black", textAlign: "center", width: "100vw"}}
        className={`${poppins.className} antialiased`}
      >
        <Navigation/>
        {children}
      </body>
    </html>
  );
}
